language: python
python:
- '3.5'
addons:
  apt:
    packages:
    - jpegoptim
    - optipng
    - yui-compressor
    - rsync
    - lessc
install: pip install --upgrade 'Nikola[extras,tests]'
script:
- scripts/build.sh
deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
before_deploy:
- openssl aes-256-cbc -K $encrypted_0be07feb735f_key -iv $encrypted_0be07feb735f_iv -in ./scripts/.deploy_key.enc -out ~/.ssh/id_rsa -d
- chmod 400 ~/.ssh/id_rsa
before_install:
- openssl aes-256-cbc -K $encrypted_9965f1701517_key -iv $encrypted_9965f1701517_iv
  -in scripts/CDN_purge.sh.enc -out scripts/CDN_purge.sh -d
